Style/StringLiterals:
  Enabled: false
  ConsistentQuotesInMultiline: true

Style/TernaryParentheses:
  EnforcedStyle: require_parentheses_when_complex

Style/MultilineIfThen:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/IndentationWidth:
  Width: 4

Layout/MultilineHashBraceLayout:
  EnforcedStyle: new_line

Metrics/LineLength:
  Max: 160

Metrics/ParameterLists:
  Max: 8
  CountKeywordArgs: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
